version: "3.9"

services:
  database:
    image: postgres
    container_name: database_orders
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=orders
      - POSTGRES_DB=orders_db
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: orders_api
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local